# Generated by Django 4.2.7 on 2023-11-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('primernombre', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('primerapellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundoapellido', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='m', max_length=1)),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('mail', models.CharField(max_length=50, verbose_name='Mail')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('discapacidad', models.CharField(max_length=50, verbose_name='Discapacidad')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': ['run', 'primernombre', 'primerapellido', 'segundoapellido'],
            },
        ),
    ]
