# Generated by Django 4.2.7 on 2023-11-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
    ]
